/*
 * Decompiled source code for SL-AC.dll
 * 
 * NOTE: This file was generated by automated decompilation using radare2.
 * The original binary is protected with Themida, so most code sections
 * are encrypted/virtualized. Only functions that could be identified
 * and decompiled from non-protected sections are included here.
 * The decompiled pseudocode may not be compilable C code.
 */

/* ============================================ */
/*  IMPORTS                                     */
/* ============================================ */

// kernel32.dll: GetModuleHandleA
// api-ms-win-core-synch-l1-2-0.dll: WaitOnAddress
// WINHTTP.dll: WinHttpGetIEProxyConfigForCurrentUser
// ws2_32: Ordinal_115
// ntdll.dll: RtlVirtualUnwind
// CRYPT32.dll: CertGetIntendedKeyUsage
// SHLWAPI.dll: PathFileExistsW
// USER32.dll: EnumWindows
// ADVAPI32.dll: CryptGetUserKey
// SHELL32.dll: SHGetFolderPathW
// Normaliz.dll: IdnToAscii
// IPHLPAPI.DLL: if_nametoindex
// Secur32.dll: InitSecurityInterfaceW

/* ============================================ */
/*  EXPORTS                                     */
/* ============================================ */

// Export [1]: FreeLpString @ 0x180127150
// Export [2]: GetConfig @ 0x180127000
// Export [3]: PollAsync @ 0x180126dc0
// Export [4]: SendRequest @ 0x180127020
// Export [5]: SendRequestAsync @ 0x1801270c0

/* ============================================ */
/*  DECOMPILED FUNCTIONS (55 functions)      */
/* ============================================ */

/* ---- Function 1/55 ---- */

int entry0 (int esi, int edx) {
    loc_0x1811d6058:
        0x1811d61df  () // 0x1811d61df(0x0, 0x0, 0x0, 0x0)
        push  (r10)
        r10 = rsp
        push  (r10)
        rsi = qword [r10 + 0x10]
        rdi = qword [r10 + 0x20]
        cl
        dl = 0x80    // 128
         // do {
    loc_0x1811d606f:
        // CODE XREF from entry0 @ 0x1811d6089
        al = byte [rsi]
        rsi+
        byte [rdi] = al
        rdi+
        ebx = 2
         // } while (?);
        }
        return eax;
    loc_0x1811d607e: // orphan
             // CODE XREFS from entry0 @ 0x1811d60f4, 0x1811d6147, 0x1811d6191, 0x1811d61a8, 0x1811d61cd
             dl += dl
             if  (var) goto loc_0x1811d6089 // unlikely

    loc_0x1811d6082: // orphan
         dl = byte [rsi]
         rsi+
         dl += dl

    loc_0x1811d6089: // orphan
         // CODE XREF from entry0 @ 0x1811d6080
         jae 0x1811d606f          // likely

    loc_0x1811d608b: // orphan
         dl += dl
         if  (var) goto loc_0x1811d6096 // unlikely

    loc_0x1811d608f: // orphan
         dl = byte [rsi]
         rsi+
         dl += dl

    loc_0x1811d6096: // orphan
         // CODE XREF from entry0 @ 0x1811d608d
         jae 0x1811d60f6          // likely

    loc_0x1811d6098: // orphan
         eax = 0
         dl += dl
         if  (var) goto loc_0x1811d60a5 // unlikely

    loc_0x1811d609e: // orphan
         dl = byte [rsi]
         rsi+
         dl += dl

    loc_0x1811d60a5: // orphan
         // CODE XREF from entry0 @ 0x1811d609c
         jae 0x1811d61ad          // likely

    loc_0x1811d60ab: // orphan
         dl += dl
         if  (var) goto loc_0x1811d60b6 // unlikely

    loc_0x1811d60af: // orphan
         dl = byte [rsi]
         rsi+
         dl += dl

    loc_0x1811d60b6: // orphan
         // CODE XREF from entry0 @ 0x1811d60ad
         eax += eax
         dl += dl
         if  (var) goto loc_0x1811d60c3 // unlikely

    loc_0x1811d60bc: // orphan
         dl = byte [rsi]
         rsi+
         dl += dl

    loc_0x1811d60c3: // orphan
         // CODE XREF from entry0 @ 0x1811d60ba
         eax += eax
         dl += dl
         if  (var) goto loc_0x1811d60d0 // unlikely

    loc_0x1811d60c9: // orphan
         dl = byte [rsi]
         rsi+
         dl += dl

    loc_0x1811d60d0: // orphan
         // CODE XREF from entry0 @ 0x1811d60c7
         eax += eax
         dl += dl
         if  (var) goto loc_0x1811d60dd // unlikely

    loc_0x1811d60d6: // orphan
         dl = byte [rsi]
         rsi+
         dl += dl

    loc_0x1811d60dd: // orphan
         // CODE XREF from entry0 @ 0x1811d60d4
         eax += eax
         if  (!var) goto loc_0x1811d60ea // likely

    loc_0x1811d60e1: // orphan
         push  (rdi)
         eax = eax
         rdi -= rax
         al = byte [rdi]
         rdi = pop  ()            // rsp

    loc_0x1811d60ea: // orphan
         // CODE XREF from entry0 @ 0x1811d60df
         byte [rdi] = al
         rdi+
         ebx = 2
         goto loc_0x1811d607e

    loc_0x1811d60f6: // orphan
         // CODE XREF from entry0 @ 0x1811d6096
         eax = 1

    loc_0x1811d60fb: // orphan
         // CODE XREF from entry0 @ 0x1811d6113
         dl += dl
         if  (var) goto loc_0x1811d6106 // unlikely

    loc_0x1811d60ff: // orphan
         dl = byte [rsi]
         rsi+
         dl += dl

    loc_0x1811d6106: // orphan
         // CODE XREF from entry0 @ 0x1811d60fd
         eax += eax
         dl += dl
         if  (var) goto loc_0x1811d6113 // unlikely

    loc_0x1811d610c: // orphan
         dl = byte [rsi]
         rsi+
         dl += dl

    loc_0x1811d6113: // orphan
         // CODE XREF from entry0 @ 0x1811d610a
         if  (((unsigned) var) < 0) goto 0x1811d60fb // unlikely

    loc_0x1811d6115: // orphan
         eax -= ebx
         ebx = 1
         if  (var) goto loc_0x1811d614c // unlikely

    loc_0x1811d611e: // orphan
         ecx = 1

    loc_0x1811d6123: // orphan
         // CODE XREF from entry0 @ 0x1811d613b
         dl += dl
         if  (var) goto loc_0x1811d612e // unlikely

    loc_0x1811d6127: // orphan
         dl = byte [rsi]
         rsi+
         dl += dl

    loc_0x1811d612e: // orphan
         // CODE XREF from entry0 @ 0x1811d6125
         ecx += ecx
         dl += dl
         if  (var) goto loc_0x1811d613b // unlikely

    loc_0x1811d6134: // orphan
         dl = byte [rsi]
         rsi+
         dl += dl

    loc_0x1811d613b: // orphan
         // CODE XREF from entry0 @ 0x1811d6132
         if  (((unsigned) var) < 0) goto 0x1811d6123 // unlikely

    loc_0x1811d613d: // orphan
         push  (rsi)
         rsi = rdi
         rsi -= rbp
         rep movsb byte [rdi],yte ptr [rsi]
         rsi = pop  ()            // rsp
         goto loc_0x1811d607e

    loc_0x1811d614c: // orphan
         // CODE XREF from entry0 @ 0x1811d611c
         eax-
         eax <<<= 8
         al = byte [rsi]
         rsi+
         ebp = eax
         ecx = 1

    loc_0x1811d615d: // orphan
         // CODE XREF from entry0 @ 0x1811d6175
         dl += dl
         if  (var) goto loc_0x1811d6168 // unlikely

    loc_0x1811d6161: // orphan
         dl = byte [rsi]
         rsi+
         dl += dl

    loc_0x1811d6168: // orphan
         // CODE XREF from entry0 @ 0x1811d615f
         ecx += ecx
         dl += dl
         if  (var) goto loc_0x1811d6175 // unlikely

    loc_0x1811d616e: // orphan
         dl = byte [rsi]
         rsi+
         dl += dl

    loc_0x1811d6175: // orphan
         // CODE XREF from entry0 @ 0x1811d616c
         if  (((unsigned) var) < 0) goto 0x1811d615d // unlikely

    loc_0x1811d6177: // orphan
         var = eax - 0x7d00
         jae 0x1811d619b          // unlikely

    loc_0x1811d617e: // orphan
         var = eax - 0x500        // 1280
         if  (((unsigned) var) < 0) goto 0x1811d6196 // likely

    loc_0x1811d6185: // orphan
         ecx+
         push  (rsi)
         rsi = rdi
         rsi -= rax
         rep movsb byte [rdi],yte ptr [rsi]
         rsi = pop  ()            // rsp
         goto loc_0x1811d607e

    loc_0x1811d6196: // orphan
         // CODE XREF from entry0 @ 0x1811d6183
         var = eax - 0x7f         // 127
         if  (((unsigned) var) > 0) goto 0x1811d619e // unlikely

    loc_0x1811d619b: // orphan
         // CODE XREF from entry0 @ 0x1811d617c
         ecx += 2

    loc_0x1811d619e: // orphan
         // CODE XREF from entry0 @ 0x1811d6199
         push  (rsi)
         rsi = rdi
         rsi -= rax
         rep movsb byte [rdi],yte ptr [rsi]
         rsi = pop  ()            // rsp
         goto loc_0x1811d607e

    loc_0x1811d61ad: // orphan
         // CODE XREF from entry0 @ 0x1811d60a5
         al = byte [rsi]
         rsi+
         ecx = 0
         al >>>= 1
         if  (!var) goto loc_0x1811d61d2 // likely

    loc_0x1811d61b9: // orphan
         ecx += 2
         ebp = eax
         push  (rsi)
         rsi = rdi
         rsi -= rax
         rep movsb byte [rdi],yte ptr [rsi]
         rsi = pop  ()            // rsp
         ebx = 1
         goto loc_0x1811d607e

    loc_0x1811d61d2: // orphan
         // CODE XREF from entry0 @ 0x1811d61b7
         r10 = pop  ()
         rdi -= qword [r10 + 0x20]
         eax = edi
         r10 = pop  ()
         retur

}

/* ---- Function 2/55 ---- */
int fcn.18007e220 (int esi, int edx) {
    loc_0x18007e220:
        // CALL XREF from fcn.181580082 @ +0x26c34
        var = dword [r13 + r10*4 + 0x4d] - r9d // arg4
        byte [0x1955aea74],h = dh,byte [rip + 0x15530849]
        stosq qword [rdi],ax
        var = edx - dword [rdx + 0x2f] // arg2
        al &= 0x4b   // 75
        dh = 0x4a    // 'J' // 74
        eax,edi = edi,ax
        byte [rcx] += bl // arg1
        edx = edx - dword [rcx] // arg2
        rdx = pop  ()
        byte [rbx + 0x2f] -= dh
        al = io[ 0x65 ]
        movsb byte [rdi],yte ptr [rsi]
        // CODE XREF from fcn.180022460 @ +0x5bd84
        bl -= byte [rax - 0x2e]
        rdi = pop  ()
         // (break)
}

/* ---- Function 3/55 ---- */
int fcn.1800e7be9 (int esi, int edx) {
    loc_0x1800e7be9:
        // CALL XREF from fcn.1811f11da @ +0x14223
        push  (0xffffffffffffffd6)
         // (break)
}

/* ---- Function 4/55 ---- */
int fcn.18011f2ad (int esi, int edx) {
    loc_0x18011f2ad:
        // CALL XREF from fcn.180144988 @ +0x17fa4
        al ^= 0xe4   // 228
        eax,edx = edx,ax // arg2
        byte [rcx - 0x2793d810] &= ah // arg1
        eax,ebp = ebp,ax // rsp // rsp
         // (break)
}

/* ---- Function 5/55 ---- */
int fcn.1801239c9 (int esi, int edx) {
    loc_0x1801239c9:
        // CALL XREF from fcn.18145563b @ +0x12496
        dl &= dl
         // (break)
}

/* ---- Function 6/55 ---- */
int sym.SL_AC.dll_PollAsync (int esi, int edx) {
    loc_0x180126dc0:
        jo 0x1bf4f462e // unlikely
         // (break)
    loc_0x180126dc6: // orphan
             push  (rdi)
             dword [0x24d469c54e2d29eb] = eax // [0x24d469c54e2d29eb:4]=-1
             // CODE XREF from fcn.1801239c9 @ +0x33f6
             dword [rcx] += edx       // arg2
             dword [rdx - 0x62] ~= dword [rdx - 0x62] // arg2
             esp ^= esi
             // CODE XREF from fcn.1801239c9 @ +0x33c2
             edx += ebx               // arg2
             io[ dx ] = eax
             // CODE XREF from sym.SL_AC.dll_PollAsync @ +0x5c
             stosb byte [rdi],l
             qword [r8] &= r15        // arg3
             al += 0x67
             al &= 0x13               // 19
             retur                    // rsp

}

/* ---- Function 7/55 ---- */
int sym.SL_AC.dll_GetConfig (int esi, int edx) {
    loc_0x180127000:
        al = byte [0xb03e4c5070be4efe]
        rdi = pop  ()
         // (break)
}

/* ---- Function 8/55 ---- */
int sym.SL_AC.dll_SendRequest (int esi, int edx) {
    loc_0x180127020:
        var = al - cl
        al = io[ 0x1a ]
         // (break)
}

/* ---- Function 9/55 ---- */
int sym.SL_AC.dll_SendRequestAsync (int esi, int edx) {
    loc_0x1801270bc:
        stosb byte [rdi],l
        edx = edx - dword [rsi - 0x78] // arg2
         // do {
    loc_0x1801270c0:
        jno 0x1801270bc // likely
         // } while (?);
        }
        return eax;
    loc_0x1801270c2:
        io[ 0x4a ] = eax
         // (break)
}

/* ---- Function 10/55 ---- */
int sym.SL_AC.dll_FreeLpString (int esi, int edx) {
    loc_0x180127150:
        ebx |= dword [rax + 0x34]
        dword [rdi] += esi
         // (break)
}

/* ---- Function 11/55 ---- */
int fcn.180144988 (int esi, int edx) {
    loc_0x180144988:
        // CALL XREF from fcn.181651f11 @ +0x8911
        push  (rsi)
         // (break)
}

/* ---- Function 12/55 ---- */
int fcn.18015f58a (int esi, int edx) {
    loc_0x18015f58a:
        // CALL XREF from fcn.181279196 @ +0x371d3
        xlat
        eax = 0xc24c194f
        ecx = ecx * 0xffffffd4
        io[ dx ] = al
         // (break)
}

/* ---- Function 13/55 ---- */
int fcn.18016f7ef (int esi, int edx) {
    loc_0x18016f7a3:
        bl -= byte [rax + 0x7b]
        var = eax - 0x64945af
         // (break)
    loc_0x18016f7ef: // orphan
               // CALL XREF from fcn.181391d13 @ +0xfcb
             if  (((unsigned) var) < 0) goto 0x18016f7a3 // unlikely

    loc_0x18016f7f2: // orphan
         cm
         byte [rsi] ^= bh
         ebx = 0xd3b999e1
         byte [rbx],l = dl,byte [rbx]

}

/* ---- Function 14/55 ---- */
int fcn.180178e7a (int esi, int edx) {
    loc_0x180178e7a:
        // CALL XREF from fcn.18007e220 @ +0x650bc
        eax ^= 0x3cfa6b66
        wai
        byte [r10 + 0x65] += cl
        dword [rdi - 6] >>>= 1
        ch -= byte cs:[rax + 0x5b]
         // (break)
}

/* ---- Function 15/55 ---- */
int fcn.180188f4b (int esi, int edx) {
    loc_0x180188f4b:
        // CALL XREF from fcn.1813137fb @ +0xe161
        rcr rbx,l
        bl -= byte [rsi + 0x501528c6]
        if  (((unsigned) var) > 0) goto 0x180188fba // unlikely
         // (break)
    loc_0x180188f56: // orphan
             var = cl - cl
             eax |= 0x96a9d4be
             rdx = pop  ()
             cl

}

/* ---- Function 16/55 ---- */
int fcn.180191587 (int esi, int edx) {
    loc_0x180191587:
        // CALL XREF from fcn.1813137fb @ +0x1d7fc
        movsb byte [rdi],yte ptr [rsi]
        esp = dword [rcx] * 0x24
        ebp += dword [rdi - 0x5a6ea6b0]
        insb byte [rdi],x
        rbp = pop  ()
         // (break)
}

/* ---- Function 17/55 ---- */
int fcn.180197943 (int esi, int edx) {
    loc_0x180197943:
        // CALL XREF from fcn.1811f11da @ +0x29446
        lodsb al,yte ds:[rsi]
        esi = 0x257cc58a
        eax = dword [0x55d9254e78ca6e28] // [0x55d9254e78ca6e28:4]=-1
        int
         // (break)
}

/* ---- Function 18/55 ---- */
int fcn.1801a74f0 (int esi, int edx) {
    loc_0x1801a7499:
        // CODE XREF from fcn.1801a74f0 @ 0x1801a74f2
        lodsb al,yte [rsi]
         // (break)
    loc_0x1801a74f0: // orphan
               // CALL XREF from fcn.1801a74f0 @ +0x26733
             rbx = pop  ()
             rsp = pop  ()
             if  (var) goto loc_0x1801a7499 // likely

    loc_0x1801a74f4: // orphan
         cwd
         while  (CX != 0) { var = *(DS*16 + SI) - *(ES*16 + DI)// SI++// DI++// CX--// if (!var) break// }
         r8 = qword [r11 + 0x68] * 0x62
         outsb dx,yte [rsi]
         fnstcw word [rbp - 0x5f67a1fa]
         byte [rax - 0x6594145] = byte [rax - 0x6594145] - dh
         var = al & 0xba          // 186
         bh = bh - byte [rax + 0x34]
         ah = ah - byte [rsi + 0x77]
         al -= 0xae               // 174
         al = byte [0xa7aec093bb5b5b99]
         var = dword [rax + 0x7e] - 0x60
         re

}

/* ---- Function 19/55 ---- */
int fcn.1801e91d0 (int esi, int edx) {
    loc_0x1801e91d0:
        // CALL XREF from section.________ @ +0x163c4
        byte [r11] += r9b
         // (break)
}

/* ---- Function 20/55 ---- */
int fcn.18021a2f4 (int esi, int edx) {
    loc_0x18021a2f4:
        // CALL XREF from fcn.1801a74f0 @ +0x192ad
        if  (((unsigned) var) > 0) goto 0x18021a371 // likely
         // (break)
    loc_0x18021a2f7: // orphan
             if  (var > 0) goto loc_0x18021a35f // likely

    loc_0x18021a2fa: // orphan
         ecx = 0x4afb899f
         eax,edx = edx,ax         // arg2
         st
         al = 0xc8                // 200
         edx += edi               // arg2
         rdx = pop  ()
         al &= 0x10               // 16

}

/* ---- Function 21/55 ---- */
int fcn.180224c7b (int esi, int edx) {
    loc_0x180224c7b:
        // CALL XREF from fcn.181410436 @ +0x4222f
        stosd dword [rdi],ax
        push  (rdx)  // arg2
        edx = 0xf54def16
         // (break)
}

/* ---- Function 22/55 ---- */
int fcn.18023ef37 (int esi, int edx) {
    loc_0x18023eebd:
        eax |= 0xc7909daa
        dword [0x7315dd40050dedb7] = eax // [0x7315dd40050dedb7:4]=-1
         // do {
    loc_0x18023eecc:
        if  (!var) goto loc_0x18023eebd // unlikely
         // } while (?);
        }
        return eax;
    loc_0x18023eece:
        // CODE XREF from fcn.180224c7b @ +0x1a1fd
        push  (rsi)
        push  (rbp)
        bl = bl - bl
        r8 = pop  () // rsp
        // CODE XREF from fcn.180224c7b @ +0x1a27d
        push  (0x5595a99e)
         // (break)
    loc_0x18023ef37: // orphan
               // CALL XREF from fcn.1813137fb @ +0x14cd
             if  (var > 0) goto loc_0x18023eecc // likely

    loc_0x18023ef39: // orphan
         cl
         ebx += ebp               // rsp
         edi = 0x25281c6a         // 'j\x1c(%'
         rol esi,l
         dl = 0x6f                // 'o' // 111
         wai
         rsp = pop  ()
         eax += 0x71cf93c8

}

/* ---- Function 23/55 ---- */
int entry0 (int esi, int edx) {
    loc_0x1811d6058:
        0x1811d61df  () // 0x1811d61df(0x0, 0x0, 0x0, 0x0)
        push  (r10)
        r10 = rsp
        push  (r10)
        rsi = qword [r10 + 0x10]
        rdi = qword [r10 + 0x20]
        cl
        dl = 0x80    // 128
         // do {
    loc_0x1811d606f:
        // CODE XREF from entry0 @ 0x1811d6089
        al = byte [rsi]
        rsi+
        byte [rdi] = al
        rdi+
        ebx = 2
         // } while (?);
        }
        return eax;
    loc_0x1811d607e: // orphan
             // CODE XREFS from entry0 @ 0x1811d60f4, 0x1811d6147, 0x1811d6191, 0x1811d61a8, 0x1811d61cd
             dl += dl
             if  (var) goto loc_0x1811d6089 // unlikely

    loc_0x1811d6082: // orphan
         dl = byte [rsi]
         rsi+
         dl += dl

    loc_0x1811d6089: // orphan
         // CODE XREF from entry0 @ 0x1811d6080
         jae 0x1811d606f          // likely

    loc_0x1811d608b: // orphan
         dl += dl
         if  (var) goto loc_0x1811d6096 // unlikely

    loc_0x1811d608f: // orphan
         dl = byte [rsi]
         rsi+
         dl += dl

    loc_0x1811d6096: // orphan
         // CODE XREF from entry0 @ 0x1811d608d
         jae 0x1811d60f6          // likely

    loc_0x1811d6098: // orphan
         eax = 0
         dl += dl
         if  (var) goto loc_0x1811d60a5 // unlikely

    loc_0x1811d609e: // orphan
         dl = byte [rsi]
         rsi+
         dl += dl

    loc_0x1811d60a5: // orphan
         // CODE XREF from entry0 @ 0x1811d609c
         jae 0x1811d61ad          // likely

    loc_0x1811d60ab: // orphan
         dl += dl
         if  (var) goto loc_0x1811d60b6 // unlikely

    loc_0x1811d60af: // orphan
         dl = byte [rsi]
         rsi+
         dl += dl

    loc_0x1811d60b6: // orphan
         // CODE XREF from entry0 @ 0x1811d60ad
         eax += eax
         dl += dl
         if  (var) goto loc_0x1811d60c3 // unlikely

    loc_0x1811d60bc: // orphan
         dl = byte [rsi]
         rsi+
         dl += dl

    loc_0x1811d60c3: // orphan
         // CODE XREF from entry0 @ 0x1811d60ba
         eax += eax
         dl += dl
         if  (var) goto loc_0x1811d60d0 // unlikely

    loc_0x1811d60c9: // orphan
         dl = byte [rsi]
         rsi+
         dl += dl

    loc_0x1811d60d0: // orphan
         // CODE XREF from entry0 @ 0x1811d60c7
         eax += eax
         dl += dl
         if  (var) goto loc_0x1811d60dd // unlikely

    loc_0x1811d60d6: // orphan
         dl = byte [rsi]
         rsi+
         dl += dl

    loc_0x1811d60dd: // orphan
         // CODE XREF from entry0 @ 0x1811d60d4
         eax += eax
         if  (!var) goto loc_0x1811d60ea // likely

    loc_0x1811d60e1: // orphan
         push  (rdi)
         eax = eax
         rdi -= rax
         al = byte [rdi]
         rdi = pop  ()            // rsp

    loc_0x1811d60ea: // orphan
         // CODE XREF from entry0 @ 0x1811d60df
         byte [rdi] = al
         rdi+
         ebx = 2
         goto loc_0x1811d607e

    loc_0x1811d60f6: // orphan
         // CODE XREF from entry0 @ 0x1811d6096
         eax = 1

    loc_0x1811d60fb: // orphan
         // CODE XREF from entry0 @ 0x1811d6113
         dl += dl
         if  (var) goto loc_0x1811d6106 // unlikely

    loc_0x1811d60ff: // orphan
         dl = byte [rsi]
         rsi+
         dl += dl

    loc_0x1811d6106: // orphan
         // CODE XREF from entry0 @ 0x1811d60fd
         eax += eax
         dl += dl
         if  (var) goto loc_0x1811d6113 // unlikely

    loc_0x1811d610c: // orphan
         dl = byte [rsi]
         rsi+
         dl += dl

    loc_0x1811d6113: // orphan
         // CODE XREF from entry0 @ 0x1811d610a
         if  (((unsigned) var) < 0) goto 0x1811d60fb // unlikely

    loc_0x1811d6115: // orphan
         eax -= ebx
         ebx = 1
         if  (var) goto loc_0x1811d614c // unlikely

    loc_0x1811d611e: // orphan
         ecx = 1

    loc_0x1811d6123: // orphan
         // CODE XREF from entry0 @ 0x1811d613b
         dl += dl
         if  (var) goto loc_0x1811d612e // unlikely

    loc_0x1811d6127: // orphan
         dl = byte [rsi]
         rsi+
         dl += dl

    loc_0x1811d612e: // orphan
         // CODE XREF from entry0 @ 0x1811d6125
         ecx += ecx
         dl += dl
         if  (var) goto loc_0x1811d613b // unlikely

    loc_0x1811d6134: // orphan
         dl = byte [rsi]
         rsi+
         dl += dl

    loc_0x1811d613b: // orphan
         // CODE XREF from entry0 @ 0x1811d6132
         if  (((unsigned) var) < 0) goto 0x1811d6123 // unlikely

    loc_0x1811d613d: // orphan
         push  (rsi)
         rsi = rdi
         rsi -= rbp
         rep movsb byte [rdi],yte ptr [rsi]
         rsi = pop  ()            // rsp
         goto loc_0x1811d607e

    loc_0x1811d614c: // orphan
         // CODE XREF from entry0 @ 0x1811d611c
         eax-
         eax <<<= 8
         al = byte [rsi]
         rsi+
         ebp = eax
         ecx = 1

    loc_0x1811d615d: // orphan
         // CODE XREF from entry0 @ 0x1811d6175
         dl += dl
         if  (var) goto loc_0x1811d6168 // unlikely

    loc_0x1811d6161: // orphan
         dl = byte [rsi]
         rsi+
         dl += dl

    loc_0x1811d6168: // orphan
         // CODE XREF from entry0 @ 0x1811d615f
         ecx += ecx
         dl += dl
         if  (var) goto loc_0x1811d6175 // unlikely

    loc_0x1811d616e: // orphan
         dl = byte [rsi]
         rsi+
         dl += dl

    loc_0x1811d6175: // orphan
         // CODE XREF from entry0 @ 0x1811d616c
         if  (((unsigned) var) < 0) goto 0x1811d615d // unlikely

    loc_0x1811d6177: // orphan
         var = eax - 0x7d00
         jae 0x1811d619b          // unlikely

    loc_0x1811d617e: // orphan
         var = eax - 0x500        // 1280
         if  (((unsigned) var) < 0) goto 0x1811d6196 // likely

    loc_0x1811d6185: // orphan
         ecx+
         push  (rsi)
         rsi = rdi
         rsi -= rax
         rep movsb byte [rdi],yte ptr [rsi]
         rsi = pop  ()            // rsp
         goto loc_0x1811d607e

    loc_0x1811d6196: // orphan
         // CODE XREF from entry0 @ 0x1811d6183
         var = eax - 0x7f         // 127
         if  (((unsigned) var) > 0) goto 0x1811d619e // unlikely

    loc_0x1811d619b: // orphan
         // CODE XREF from entry0 @ 0x1811d617c
         ecx += 2

    loc_0x1811d619e: // orphan
         // CODE XREF from entry0 @ 0x1811d6199
         push  (rsi)
         rsi = rdi
         rsi -= rax
         rep movsb byte [rdi],yte ptr [rsi]
         rsi = pop  ()            // rsp
         goto loc_0x1811d607e

    loc_0x1811d61ad: // orphan
         // CODE XREF from entry0 @ 0x1811d60a5
         al = byte [rsi]
         rsi+
         ecx = 0
         al >>>= 1
         if  (!var) goto loc_0x1811d61d2 // likely

    loc_0x1811d61b9: // orphan
         ecx += 2
         ebp = eax
         push  (rsi)
         rsi = rdi
         rsi -= rax
         rep movsb byte [rdi],yte ptr [rsi]
         rsi = pop  ()            // rsp
         ebx = 1
         goto loc_0x1811d607e

    loc_0x1811d61d2: // orphan
         // CODE XREF from entry0 @ 0x1811d61b7
         r10 = pop  ()
         rdi -= qword [r10 + 0x20]
         eax = edi
         r10 = pop  ()
         retur

}

/* ---- Function 24/55 ---- */
int fcn.1811edefa (int esi, int edx) {
    loc_0x1811ede86:
        popf
        al = io[ dx ]
        bpl = 0x2c   // ',' // 44
        retf 0x97ce
         // (break)
    loc_0x1811edefa: // orphan
               // CALL XREF from fcn.181279196 @ +0x335c7
             rsi = pop  ()
             jno 0x1811ede86          // likely

    loc_0x1811edefd: // orphan
         retf 0x5101

}

/* ---- Function 25/55 ---- */
int fcn.1811f11da (int esi, int edx) {
    loc_0x1811f11da:
        // CALL XREF from fcn.1812c8cf7 @ +0x3e23a
        al += 0x4c
        al = byte [0xff5ec4a9a5eefc4a]
        var = al - 0x52 // 82
        hl
         // (break)
}

/* ---- Function 26/55 ---- */
int fcn.1812201d7 (int esi, int edx) {
    loc_0x1812201cd:
        // CODE XREF from fcn.1812201d7 @ 0x1812201d9
        retf 0x327b
         // (break)
    loc_0x1812201d7: // orphan
               // CALL XREF from fcn.180224c7b @ +0x1da2
             al = byte [rcx]          // arg1
             if  (var >= 0) goto loc_0x1812201cd // likely

    loc_0x1812201db: // orphan
         // CODE XREF from fcn.1812201d7 @ +0x5b
         eax,ecx = ecx,ax         // arg1
         word [rsi] = ss
         retur

}

/* ---- Function 27/55 ---- */
int fcn.18123bcbf (int esi, int edx) {
    loc_0x18123bc67:
        // CODE XREF from fcn.18123bcbf @ 0x18123bcbf
        rdi = dword [rbx]
        ch = 0x65    // 'e' // 101
        rcl dword [0x166a85466],l
         // (break)
    loc_0x18123bcbf: // orphan
               // CALL XREF from fcn.1813137fb @ +0x20115
             loope 0x18123bc67        // likely

    loc_0x18123bcc1: // orphan
         var = byte [r14 + r13*4 - 0x1aaa1563] & r13b
         var = al & 0x2b          // 43
         jae 0x18123bd26          // likely

    loc_0x18123bd26: // orphan
         // CODE XREF from fcn.18123bcbf @ 0x18123bccc
         eax,edi = edi,ax

}

/* ---- Function 28/55 ---- */
failed to retrieve block at 0x131f05cb6
int fcn.181279196 (int esi, int edx) {
    loc_0x181279196:
        // CALL XREF from fcn.181651f11 @ +0x27ed
        edx = rax
        if  (((unsigned) var) <= 0) goto 0x131f05cb6 // unlikely
        // chop
    loc_0x18127919e: // orphan
             retur

}

/* ---- Function 29/55 ---- */
int fcn.1812c8cf7 (int esi, int edx) {
    loc_0x1812c8cb0:
        var = al & 0xd7 // 215
        ch = 0xc4    // 196
        wai
        var = eax & 0xeacdfe92
        ~   eax += 0x3ef1e1a0
        // CODE XREF from fcn.1812c8cf7 @ 0x1812c8d36
        loope 0x1812c8cb0 // likely
        rdi = eax
         // do {
    loc_0x1812c8cc2:
        al += 0x28   // 40
         // } while (?);
        }
        return eax;
    loc_0x1812c8cbd: // orphan
             // CODE XREF from fcn.1812c8cf7 @ 0x1812c8d36
             loope 0x1812c8cb0        // likely

    loc_0x1812c8cbf: // orphan
         rdi = eax

    loc_0x1812c8cf7: // orphan
           // CALL XREF from fcn.1800e7be9 @ +0x170ba
         ecx &= ebx               // arg1
         ecx <<= 1                // arg1
         cmpsd dword [rsi],word ptr [rdi]
         if  (var >= 0) goto loc_0x1812c8d31 // likely

    loc_0x1812c8cff: // orphan
         eax,ecx = ecx,ax         // arg1
     ~   ecx |= edi               // arg1
         // CODE XREF from fcn.1812c8cf7 @ 0x1812c8d34
         st

    loc_0x1812c8d01: // orphan
         // CODE XREF from fcn.1812c8cf7 @ 0x1812c8d34
         st

    loc_0x1812c8d02: // orphan
         io[ dx ] = al

    loc_0x1812c8d31: // orphan
         // CODE XREF from fcn.1812c8cf7 @ 0x1812c8cfc
         outsb dx,yte [rsi]
         rdx = pop  ()
         rsi = pop  ()
         jo 0x1812c8d01           // unlikely

    loc_0x1812c8d36: // orphan
         if  (((unsigned) var) < 0) goto 0x1812c8cbd // unlikely

    loc_0x1812c8d38: // orphan
         ebp = 0xa4aa98f8
         outsb dx,yte [rsi]

}

/* ---- Function 30/55 ---- */
int fcn.1813137fb (int esi, int edx) {
    loc_0x1813137ab:
        // CODE XREF from fcn.1813137fb @ 0x181313800
        rsi = pop  ()
        bl = 0x60    // '`' // 96
        goto loc_0x1de0a34a9
         // (break)
    loc_0x1813137fb: // orphan
               // CALL XREF from fcn.181580082 @ +0x425e2
             eax &= 0xc1943b31
             loopne 0x1813137ab       // likely

    loc_0x181313803: // orphan
         al = io[ dx ]
         byte [rsi - 0x17843a4f] >>= cl
         cwd
         ch = 0x12                // 18
         cm
         eax += 0xfbf709de
         io[ 0x60 ] = eax

}

/* ---- Function 31/55 ---- */
int fcn.181391d13 (int esi, int edx) {
    loc_0x181391cd9:
        // CODE XREF from fcn.181391d13 @ 0x181391d1f
        edi = 0x9019100f
        ebp += eax   // rsp
        push  (cpuflags)
        dh &= bh
        eax,esp = esp,ax
         // (break)
    loc_0x181391cf5: // orphan
             // CODE XREF from fcn.181391d13 @ 0x181391d1a
             al |= 0x40               // 64
             cl

    loc_0x181391d13: // orphan
           // CALL XREF from fcn.18023ef37 @ +0x27c73
         if  (var) goto loc_0x181391d55 // likely

    loc_0x181391d16: // orphan
         edx |= dword [rax - 1]   // arg2
         jae 0x181391cf5          // likely

    loc_0x181391d1c: // orphan
         var = dword [rsi - 0x29] & ebx
         goto loc_0x181391cd9

    loc_0x181391d55: // orphan
         // CODE XREF from fcn.181391d13 @ 0x181391d13
         r10 = r10
         dword [rax] = edi

}

/* ---- Function 32/55 ---- */
int fcn.18139e3ba (int esi, int edx) {
    loc_0x18139e3ba:
        // CALL XREF from fcn.1800e7be9 @ +0x156a7
        esp = 0x620984d0
        edi = edi - ebx
        ebx = edi * 0x6840be5b
         // (break)
}

/* ---- Function 33/55 ---- */
int fcn.1813a4e2d (int esi, int edx) {
    loc_0x1813a4e2d:
        // CALL XREF from fcn.1813137fb @ +0x3b40d
        ebx -= dword [rax]
        esp = 0x3e161107
         // (break)
}

/* ---- Function 34/55 ---- */
int fcn.1813cdec3 (int esi, int edx) {
    loc_0x1813cdec3:
        // CALL XREF from fcn.1813137fb @ +0x79cf5
        eax += 0x5cd1264c
         // (break)
}

/* ---- Function 35/55 ---- */
int fcn.181410436 (int esi, int edx) {
    loc_0x181410436:
        // CALL XREF from fcn.1813137fb @ +0x65bf7
        byte [rdx + 0x75] <<<= 9 // arg2
        al = byte [0x7efb6d672d01de55] // [0x7efb6d672d01de55:1]=255
        // CODE XREF from fcn.181410436 @ 0x181410438
        ebp = 0xf55125dc
         // (break)
}

/* ---- Function 36/55 ---- */
int fcn.18145563b (int esi, int edx) {
    loc_0x18145563b:
        // CALL XREF from fcn.180022460 @ +0x90bb
        re
         // (break)
}

/* ---- Function 37/55 ---- */
int fcn.18147c323 (int esi, int edx) {
    loc_0x18147c323:
        // CALL XREF from fcn.1813137fb @ +0x56576
        cl ^= byte [rdx - 0x1f] // arg2
        if  (((unsigned) var) <= 0) goto 0x18147c393 // unlikely
         // (break)
    loc_0x18147c328: // orphan
             int

}

/* ---- Function 38/55 ---- */
int fcn.1814976a5 (int esi, int edx) {
    loc_0x1814976a5:
        // CALL XREF from fcn.18023ef37 @ +0x3fadb
        al = al - 0x80
        var = dl - byte [rcx + rax + 0x7cf0c6e0] // arg1
        ah += ch
        if  (((unsigned) var) <= 0) goto 0x1814976bb // likely
            
    loc_0x1814976bb:
        // CODE XREFS from fcn.1814976a5 @ 0x1814976b0, 0x1814976b8
        push  (rcx)  // arg1
        cm
        dh += byte [arg_25fcd5c0h]
        lodsd eax,word [rsi]
        edi += dword [rax + 0x6200ed97]
        esp -= dword [rax - 0x52]
        push  (cpuflags)
        eax = eax * edx
         // } else {
    loc_0x1814976b3:
        edi = 0xb0a29eae
        if  (var <= 0) goto loc_0x1814976bb // unlikely
        }
        return eax;
    loc_0x1814976ba:
        eax,esp = esp,ax // rsp // rsp
}

/* ---- Function 39/55 ---- */
int fcn.1814a490b (int esi, int edx) {
    loc_0x1814a490b:
        // CALL XREF from fcn.1814bc5fc @ +0x26cd5
        push  (rbx)
        rs
        rcx = pop  () // rsp
        dl = 0x56    // 'V' // 86
        jo 0x1814a497b // unlikely
         // (break)
    loc_0x1814a4915: // orphan
             push  (rdx)              // arg2
             al -= 0x74               // 116
             ficomp dword [rcx - 0x74a5e995]
             ror byte [rdi + 0x79]
             rsp = pop  ()
             cl -= byte [rdi + 0x688998eb]
             var = dword [0x1d8c6306b] -
             eax,edx = edx,ax         // arg2
             push  (rax)
             push  (0xffffffffffffff9a)
             re

}

/* ---- Function 40/55 ---- */
int fcn.1814bc5fc (int esi, int edx) {
    loc_0x1814bc5fc:
        // CALL XREF from fcn.1813137fb @ +0x57652
        push  (rdi)
        eax ^= 0x39debdf9
        bpl -= r15b
        wai
        rol dword [rax - 0x624e758d],xf9
         // (break)
}

/* ---- Function 41/55 ---- */
failed to retrieve block at 0x1814edd8d
int fcn.1814edd7a (int esi, int edx) {
    loc_0x1814edd2d:
        // CODE XREF from fcn.1814edd7a @ 0x1814edd82
        eax = eax - 0xdb8ca84b
        esp = dword [arg_14283331h] * 0x800405f6
        if  (((unsigned) var) < 0) goto 0x1814edd8d // unlikely
        // chop
    loc_0x1814edd3f: // orphan
             ebp >>= cl
             pcmpgtd mm6,word [rcx - 0x69]
             dword [rsi + 0xc1cb923] &= 0x7e51b873 // [0x7e51b873:4]=-1
             push  (0x2d7f00fb)
             jo 0x1814eddb3           // unlikely

    loc_0x1814edd56: // orphan
         goto loc_0x1814eddd5

    loc_0x1814edd7a: // orphan
           // CALL XREF from fcn.181525d27 @ +0xca89
         io[ dx ] = eax
         dl = 0x65                // 'e' // 101
         dh += dh
         st
         ch = 0x55                // 'U' // 85
         jl 0x1814edd2d           // unlikely

    loc_0x1814edd84: // orphan
         word [rcx - 0x2596af40] = word [rcx - 0x2596af40] /
         var = edx - ebx          // arg2

    loc_0x1814eddd5: // orphan
         // CODE XREF from fcn.1814edd7a @ 0x1814edd56
         rcl byte [rsi],l
         bl += byte [rcx]
         dword [rsi - 0x7a3a9a15] |= ecx
         var = rax & 0x5553848c
         al = io[ 0xfd ]
         lodsd eax,word [rsi]

}

/* ---- Function 42/55 ---- */
int fcn.1814ffef7 (int esi, int edx) {
    loc_0x1814ffea8:
        // CODE XREF from fcn.1814ffef7 @ 0x1814fff14
        byte [r10 + 0x1f],il = dil,byte [r10 + 0x1f]
        if  (var) goto loc_0x1814ffee4 // likely
            
    loc_0x1814ffee4:
        // CODE XREF from fcn.1814ffef7 @ 0x1814ffeac
        // CODE XREF from fcn.1814ffef7 @ +0x39
        fsubr dword [rax]
        // CODE XREF from fcn.1814edd7a @ +0x120fb
        rcx = eax
         // } else {
    loc_0x1814ffef7: // orphan
               // CALL XREF from fcn.1812c8cf7 @ +0x2a923
             esi = dword [rax + 0xd2dc881]
             eax = io[ dx ]
             qword [rbx + r12*2] = r14
             rsp = dword [arg_743fd3b4h]
             al = al - 0xde
             al = byte [0xaf02b69dd2a05f4e]
             jo 0x1814ffea8           // unlikely

    loc_0x1814fff16: // orphan
         lodsb al,yte [rsi]
         byte [rsi + 0x48] += ch
         cl ^= ch
         al += 0x3e               // 62

}

/* ---- Function 43/55 ---- */
int fcn.18151359e (int esi, int edx) {
    loc_0x18151359e:
        // CALL XREF from fcn.1813137fb @ +0x64098
        push  (rdx)  // arg2
        push  (rbp)
        loopne 0x181513608 // likely
         // (break)
}

/* ---- Function 44/55 ---- */
int fcn.181525d27 (int esi, int edx) {
    loc_0x181525d27:
        // CALL XREF from fcn.1814edd7a @ +0xcebb
        push  (rbp)
         // (break)
}

/* ---- Function 45/55 ---- */
int fcn.181580082 (int esi, int edx) {
    loc_0x181580082:
        // CALL XREF from fcn.1813137fb @ +0x650d6
        var = eax - dword [rax]
        rbp = rbp - qword [r14 + r10*2 + 0xd]
        eax &= 0x8c00b1ca
        enter 0x5909,xfffffffffffffff8 // "\tY"
        eax -= 0x86003589
        dl = 0x92    // 146
         // (break)
}

/* ---- Function 46/55 ---- */
int fcn.1816465c7 (int esi, int edx) {
    loc_0x1816465c7:
        // CALL XREF from fcn.1801e91d0 @ +0x1b071
        int          // 1 = unknown ()
        loope 0x181646606 // likely
         // (break)
    loc_0x1816465ca: // orphan
             byte [rdx] &= dl         // arg2
             rsi = pop  ()
             push  (rdx)              // arg2 // rsp
             cd
             al ^= byte [rdx + rdi*4 + 0x67999cc8] // arg2
             ah >>= 0x29
             al = byte [0x3b10151c76096cbd] // [0x3b10151c76096cbd:1]=255
             ah += byte gs:[rsi + 0x2f88be22]
             enter 0x617c,x2e         // '|a' // "|a"
             eax = dword [0x93143d10c42c1f26]
             hl

}

/* ---- Function 47/55 ---- */
int fcn.181651f11 (int esi, int edx) {
    loc_0x181651ef8:
        // CODE XREF from fcn.181651f11 @ 0x181651f4c
        bl += byte [rdx] // arg2
        hl
         // (break)
    loc_0x181651f11: // orphan
               // CALL XREF from fcn.1800e7be9 @ +0xc690
             eax += 0xe2081ac7
             st
             ecx |= esp               // arg1 // rsp
             push  (cpuflags)         // "|a"
             byte [rbx] -= dl
             rcr dword [rax + 0x41],xe8
             rax,r14 = r14,ax
             loope 0x181651f59        // likely

    loc_0x181651f24: // orphan
         al = io[ 0xd9 ]
         byte [rax + 0x602308c0] = !byte [rax + 0x602308c0]
         // CODE XREF from fcn.1816465c7 @ +0xb922
         cm
         qword [r14] -= r14
         al = byte [0x6b2171b5f4c04bfb] // [0x6b2171b5f4c04bfb:1]=255
         al += 0xc5
         r15d = 0x60686370        // 'pch`'
         push  (0x25)             // '%' // 37 // "%"
         fstp qword [rbx - 0x2e]
         rsp = pop  ()
         al ^= byte [rcx + 0x53]  // arg1
         cl = bl
         if  (var > 0) goto loc_0x181651ef8 // likely

    loc_0x181651f4e: // orphan
         var = esp - dword [rbx]
         al |= 0x5b               // 91
         rcx = pop  ()
         insd dword [rdi],x
         push  (0x454b3e09)       // "\t>KE" rsp

    loc_0x181651f59: // orphan
         // CODE XREF from fcn.181651f11 @ 0x181651f22
         edi = dword [rdi + 0x15] * 0x78
         dword [rdi] = dword ptr [rsi]
         retf

}

/* ---- Function 48/55 ---- */
int fcn.18165dbce (int esi, int edx) {
    loc_0x18165dbce:
        // CALL XREF from fcn.181525d27 @ +0xb1d9
        eax = io[ dx ]
        byte [rsi - 0x72593fe2] += r8b
        io[ dx ] = al
        if  (var <= 0) goto loc_0x18165dbf8 // likely
         // (break)
    loc_0x18165dbda: // orphan
             dil &= byte [r10 - 0x677a9000]
             btc dword [rax],cx       // arg1

}

/* ---- Function 49/55 ---- */
int fcn.1816689b9 (int esi, int edx) {
    loc_0x1816689b9:
        // CALL XREF from fcn.1814a490b @ +0x1646c
        var = eax - 0x2184ce98
        byte [rbx + 0xa] += ch
        dl &= cl
        esp = esp - ebp
        xlat
        ah += bh
        sah
        scasd eax,word [rdi]
         // (break)
}

/* ---- Function 50/55 ---- */
int fcn.18169f7e4 (int esi, int edx) {
    loc_0x18169f754:
        cm
        push  (cpuflags) // "%"
        io[ dx ] = eax
        insd dword [rdi],x
        al ^= 0x10   // 16
        byte [rdx - 0x11] ^= ah // arg2
        dh += byte [rax + 0x58]
        eax &= 0x11bb8821
        retur
         // (break)
    loc_0x18169f79e: // orphan
             // CODE XREF from fcn.18169f7e4 @ 0x18169f7f0
             fild word [rbx - 0x466b96dc]
             rsi = cr6
             al ^= 0xec               // 236
             if  (var) goto loc_0x18169f754 // likely

    loc_0x18169f7ac: // orphan
         push  (rax)
         ah = 0x44                // 'D' // 68
         byte [rax] += 0xbf

    loc_0x18169f7e4: // orphan
           // CALL XREF from fcn.180022460 @ +0x3ac7f
         dword [rsi] += 0x7a      // [0x7a:4]=-1 // 122
         var = eax & 0x8403560c
         byte [rbx] &= dh
         // CODE XREF from fcn.18169f7e4 @ +0x54
         var = dword [rax] - esp
         goto loc_0x18169f79e

}

/* ---- Function 51/55 ---- */
int fcn.1816b5340 (int esi, int edx) {
    loc_0x1816b530f:
        // CODE XREF from fcn.1816b5340 @ 0x1816b535e
        eax &= dword [rdx] // arg2
        rax = rdi
        retf 0xd540
         // (break)
    loc_0x1816b5340: // orphan
               // CALL XREF from fcn.1816465c7 @ +0x86a5
             sah
             push  (0xffffffff9303e88e)
             push  (0x12)             // 18
             cl
             esi ^= eax
             dh = al
             edi = 0xaaf53002
             ficomp word [rdi]
             eax,edx = edx,ax         // arg2
             esi -= dword [rbx - 0x51aff48]
             loope 0x1816b530f        // likely

}

/* ---- Function 52/55 ---- */
int fcn.1816c1cb1 (int esi, int edx) {
    loc_0x1816c1cb1:
        // CALL XREF from fcn.18165dbce @ +0x502d
        byte [rcx - 0x37f7cbd1] |= dh // arg1
        byte [rsi + 8] = byte [rsi + 8] - al
         // (break)
}

/* ---- Function 53/55 ---- */
int fcn.1816d3d93 (int esi, int edx) {
    loc_0x1816d3d50:
        // CODE XREF from fcn.1816d3d93 @ 0x1816d3dcd
        dword [rbx] += edi
        eax,r10d = r10d,ax
        ~   push  (0x8014d41)
        // CODE XREF from fcn.1816d3d93 @ 0x1816d3dba
        qword [r8] += r9
         // do {
    loc_0x1816d3d59:
        var = al & 0x51 // 81
        eax = 0x544e3e08
        bl |= bl
        int
         // } while (?);
        }
        return eax;
    loc_0x1816d3d56: // orphan
             // CODE XREF from fcn.1816d3d93 @ 0x1816d3dba
             qword [r8] += r9

    loc_0x1816d3d93: // orphan
           // CALL XREF from fcn.1816689b9 @ +0x13510
         byte [rax] = byte [rax] - cl
         cl += byte [arg_71h]
         if  (!var) goto loc_0x1816d3e02 // likely

    loc_0x1816d3d9a: // orphan
         byte [rax] = byte [rax] - cl
         cd
         qword [rax + 0x10601991] |= rbx
         dword [rax + 0x5b] -= edi
         esp = esp                // "\t>KE" rsp
         word [rcx] = ss          // arg1
         push  (rdi)
         jl 0x1816d3dc7           // likely

    loc_0x1816d3dae: // orphan
         dword [rax + rdx*4 + 8] ^= edx // arg2
         if  (((unsigned) var) <= 0) goto 0x1816d3d81 // unlikely

    loc_0x1816d3db4: // orphan
         dword [rax + 0x62081148] |= ebp
         if  (var >= 0) goto loc_0x1816d3d56 // unlikely

    loc_0x1816d3dbc: // orphan
         byte [rax + rbx + 0x9940826] |= bh
     ~   push  (0xffffffff990818d4)
         // CODE XREF from fcn.1816d3d93 @ 0x1816d3dac
         cd

    loc_0x1816d3dc7: // orphan
         // CODE XREF from fcn.1816d3d93 @ 0x1816d3dac
         cd

    loc_0x1816d3dc8: // orphan
         byte [rcx]--             // arg1
         al = io[ 0x48 ]
         push  (cpuflags)
         if  (var <= 0) goto loc_0x1816d3d50 // likely

    loc_0x1816d3dcf: // orphan
         rcl byte [rdx + 0x4708033c],l

    loc_0x1816d3e02: // orphan
         // CODE XREF from fcn.1816d3d93 @ 0x1816d3d98
         esp |= dword [rax + rbp*8 - 0x23]
         dword [rdi] += ebx

}

/* ---- Function 54/55 ---- */
int fcn.1816e3233 (int esi, int edx) {
    loc_0x1816e31c2:
        // CODE XREF from fcn.1816e3233 @ 0x1816e3240
        eax,ecx = ecx,ax // arg1
         // (break)
    loc_0x1816e3233: // orphan
               // CALL XREF from fcn.181580082 @ +0x2d9f
             dword [rax] = ebp
             dh += byte [rax]
             al &= 0x38               // 56
             push  (rax)
             eax,ecx = ecx,ax         // arg1
             rax = pop  ()            // "\t>KE" rsp
             ah &= byte [rax + 0x44]
             js 0x1816e31c2           // unlikely

    loc_0x1816e3242: // orphan
         dword [rax - 0x57db5fee] = ecx // arg1
         al = 0x91                // 145
         enter 0xffffffffffffd022,x44
         fdiv st  (0)
         eax = edi

}

/* ---- Function 55/55 ---- */
int fcn.1816f9b46 (int esi, int edx) {
    loc_0x1816f9b46:
        // CALL XREF from fcn.1816689b9 @ +0x7276
        byte [rax + 0x5270475d] += dl
        stosb byte [rdi],l
        var = eax & 0x19e037
         // (break)
}
